# Generated by Django 4.1.4 on 2022-12-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ранг, с которого нужен буст',
                'verbose_name_plural': 'Ранги, с которых нужен буст',
            },
        ),
        migrations.CreateModel(
            name='DesiredRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ранг, до которого нужен буст',
                'verbose_name_plural': 'Ранги, до которых нужен буст',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('discount', models.BooleanField(blank=True, default=False, verbose_name='Товар со скидкой')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('current_price', models.IntegerField(verbose_name='Текущая цена')),
                ('execution_time', models.CharField(blank=True, max_length=128, verbose_name='Время выполнения')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение')),
                ('is_bestseller', models.BooleanField(blank=True, null=True, verbose_name='Бестселлер')),
                ('base_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.baserank')),
                ('desired_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.desiredrank')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Продукт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
