# Generated by Django 4.1.4 on 2023-01-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.baserank'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desired_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.desiredrank'),
        ),
    ]
