version: '3.8'

services:
  db:
    image: postgres:14.5
    volumes:
      - vlrnk_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  vlrnk_postgres_data: